apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: times-app
  name: times-app
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: nginx
    spec:
      containers:
      - image: times-registry-vpc.cn-shenzhen.cr.aliyuncs.com:443/times-new-mall-uat/times-app/:GIT_BRANCH_AS_TAG_TIMESTAMP
        name: times-app
        resources: {}
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-times-app-conf
          subPath: nginx.conf
      volumes:
      - configMap:
          name: nginx-times-app-conf
        name: nginx-times-app-conf